version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - '9020:80'
        volumes:
            - ./code:/code
            - ./code/public:/code/public
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        links:
            - php
    php:
        build: ./php-fpm
        volumes:
            - ./code:/code
            - ./code/public:/code/public
            - ./code/install:/code/install
        networks:
            - code-network
        links:
            - db
    db:
      image: mysql
      volumes:
        - /mysql/sentrifugo:/var/lib/mysql
      ports:
        - '3308:3306'
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=wordpress
      restart: always
      networks:
          - code-network

networks:
    code-network:
        driver: bridge
